#syntax=docker/dockerfile:1 

FROM node:23-slim

RUN apt-get update && apt-get install -y curl && apt-get clean

WORKDIR /frontend

# Copy only package files first
COPY package.json package-lock.json ./

# Install dependencies 
RUN npm install 

ARG INSTALL_PLAYWRIGHT=false

RUN echo "$INSTALL_PLAYWRIGHT"

# Conditionally install Playwright and its deps
RUN if [ "$INSTALL_PLAYWRIGHT" = "true" ]; then \
      npm install @playwright/test && \
      npx playwright install --with-deps; \
    fi
