services:
  db: 
    image: mysql:8.4 
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - backend-net
      - db-net
    profiles:
      - dev 
      - prod

  dbmate:
    image: amacneil/dbmate
    depends_on:
      - db
    environment:
      # - DATABASE_URL=mysql://test:password@db:3306/test_db
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}
    volumes:
      - ./db/migrations:/db/migrations
    networks:
      - db-net
    profiles:
      - dev 
      - prod
    command: ["--wait","up"]

  backend: 
    build: ./backend
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - backend-net 
      - frontend-net
    profiles:
      - dev 
      - prod

  frontend-builder:
    build: ./frontend
    volumes:
      - frontend_dist:/dist
    command: >
      sh -c "cp -r dist/. /dist"
    profiles:
      - dev 
      - prod

  nginx-dev:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    profiles:
      - dev
    networks:
      - frontend-net

  nginx-setup:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.setup.conf:/etc/nginx/templates/nginx.conf.template
    environment:
      - DOMAIN_ROOT=${DOMAIN_ROOT}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SSL_CERT=${SSL_CERT}
      - SSL_CERT_KEY=${SSL_CERT_KEY} 
    profiles:
      - staging

  certbot-setup:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - ./scripts/cert_check.sh:/scripts/cert_check.sh:ro
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - DOMAIN_ROOT=${DOMAIN_ROOT}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SSL_CERT=${SSL_CERT}
      - SSL_CERT_KEY=${SSL_CERT_KEY} 
    entrypoint: ["sh"]
    command: ["/scripts/cert_check.sh"]
    depends_on: 
      - nginx-setup
    profiles:
      - staging
  
  nginx-prod:
    image: nginx:alpine 
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.prod.conf:/etc/nginx/templates/nginx.conf.template
    env_file:
      - .env
    profiles:
      - prod
    networks:
      - frontend-net
    depends_on:
      - backend

volumes: 
  frontend_dist:
  mysql_data:
  certbot-etc:
  certbot-var:
  certbot-www:

networks:
  frontend-net:
    driver: bridge
 
  db-net:
    driver: bridge

  backend-net:
    driver: bridge
