services:
  db: 
    image: mysql:8.4 
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - backend-net 
    profiles:
      - dev 
      - prod

  backend: 
    build: ./server_backend
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - backend-net 
      - frontend-net
    profiles:
      - dev 
      - prod

  frontend-builder:
    build: ./server_frontend
    volumes:
      - frontend_dist:/dist
    command: >
      sh -c "cp -r dist/. /dist"
    profiles:
      - dev 
      - prod

  nginx-dev:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    profiles:
      - dev
    networks:
      - frontend-net

  nginx-setup:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.setup.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-www:/var/www/certbot
    profiles:
      - staging


  certbot-setup:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - ./scripts/cert_check.sh:/scripts/cert_check.sh:ro
    entrypoint: ["sh"]
    command: ["/scripts/cert_check.sh"]
    depends_on: 
      - nginx-setup
    profiles:
      - staging
  
  nginx-prod:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    profiles:
      - prod
    networks:
      - frontend-net
    depends_on:
      - backend

volumes: 
  frontend_dist:
  mysql_data:
  certbot-etc:
  certbot-var:
  certbot-www:

networks:
  frontend-net:
    driver: bridge

  backend-net:
    driver: bridge
