services:
  db: 
    image: mysql:8.4 
    volumes: 
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net 

  backend: 
    build: ./server_backend
    networks:
      - backend-net 
      - frontend-net

  frontend-builder:
    build: ./server_frontend
    volumes:
      - frontend_dist:/dist
    command: >
      sh -c "cp -r dist/. /dist"

  nginx-dev:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    profiles:
      - dev
    networks:
      - frontend-net

  nginx-prod:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    profiles:
      - prod
    networks:
      - frontend-net
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"

volumes: 
  frontend_dist:
  mysql_data:
  certbot-etc:
  certbot-var:
  certbot-www:

networks:
  frontend-net:
    driver: bridge

  backend-net:
    driver: bridge
