services:
  mysql_dev: 
    image: mysql:8.4 
    volumes: 
      - mysql_dev_data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=test_root_pass
      - MYSQL_DATABASE=test_db 
      - MYSQL_USER=test_user 
      - MYSQL_PASSWORD=test_pass
    networks:
      - backend-net
      - db-net
    profiles:
      - dev
      - dev_backend 
      - dev_frontend 

  dbmate_dev:
    image: amacneil/dbmate
    depends_on:
      - mysql_dev
    environment:
      - DATABASE_URL=mysql://test_user:test_pass@mysql_dev:3306/test_db
    volumes:
      - ./db/migrations:/db/migrations
    networks:
      - db-net
    profiles:
      - dev
      - dev_backend 
      - dev_frontend 
    command: ["--wait","up"]

  backend_dev: 
    build: ./backend
    environment:
      - MYSQL_HOST=mysql_dev
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=test_root_pass
      - MYSQL_DATABASE=test_db 
      - MYSQL_USER=test_user 
      - MYSQL_PASSWORD=test_pass
      - DATABASE_URL=mysql+pymysql://test_user:test_pass@mysql_dev:3306/test_db
      - ALLOWED_ORIGINS=["http://localhost:5173]
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_SECRET=STUFRZH-MKLFj4j-6c9Z50WNWkvd9uqiWQJOpeCtI9Q
      - JWT_REFRESH_SECRET=STUFRZH-MKLFj4j-6c9Z50WNWkvd9uqiWQJOpeCtI9Q
      - MFA_ENCRYPTION_KEY=7CrUl1rG4NBNk4bSV2uU7RW79Z_dRdvrrZn3Eqgytqg=
      - APP_URL=http://localhost:5173 
      - DEBUG=True
    env_file:
      - .env
    volumes:
      - ./scripts/wait-for-db.sh:/scripts/wait-for-db.sh
    networks:
      - backend-net 
      - frontend-net
    profiles:
      - dev
      - dev_backend 
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./backend/app
          target: /backend/app
          action: sync+restart
    entrypoint: ["/scripts/wait-for-db.sh"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" , "--reload"]

  frontend_dev:
    build: ./frontend
    environment:
      - BACKEND_URL=http://backend_dev:8000
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - 5173:5173
    networks:
      - frontend-net
    profiles:
      - dev 
      - dev_frontend
    volumes:
      - ./scripts/wait-for-backend.sh:/scripts/wait-for-backend.sh
    develop:
      watch:
        - path: ./frontend/src
          target: /frontend/src
          action: sync+restart
    entrypoint: ["/scripts/wait-for-backend.sh"]
    command: > 
      sh -c " 
        npm run dev -- --host 0.0.0.0 --port 5173
      "

volumes: 
  mysql_dev_data:

networks:
  frontend-net:
    driver: bridge
 
  db-net:
    driver: bridge

  backend-net:
    driver: bridge
