name: Renew SSL Certs Weekly

on:
  schedule:
    - cron: '0 4 * * 0' # every Sunday at 4 am UTC 

jobs: 
  renew-certs:
    runs-on: ubuntu-latest 

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_IP  }}
          username: ${{ secrets.PRODUCTION_USERNAME  }}
          key: ${{ secrets.PRODUCTION_KEY_PRIVATE  }}
          port: ${{  secrets.PRODUCTION_PORT  }}
          script: |
            cd $HOME/test_server

            chmod +x ./scripts/deploy.sh 
            ./scripts/deploy.sh

