name: Deploy to Server

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/github_actions_deploy
          chmod 600 ~/.ssh/github_actions_deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRODUCTION_KEY_PRIVATE }} 

      - name: Add SSH host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 818 $PRODUCTION_IP >> ~/.ssh/known_hosts
        env:
          PRODUCTION_IP: ${{ secrets.PRODUCTION_IP }}

      - name: SSH and pull latest code
        run: |
          ssh -i ~/.ssh/github_actions_deploy admin@$PRODUCTION_IP -p 818 << 'EOF'
            cd $HOME/test_server
            git pull origin main
          EOF
        env:
          PRODUCTION_IP: ${{ secrets.PRODUCTION_IP }}


