name: Deploy to Production 

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Multiple commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_IP  }}
          username: ${{ secrets.PRODUCTION_USERNAME  }}
          key: ${{ secrets.PRODUCTION_KEY_PRIVATE  }}
          port: ${{  secrets.PRODUCTION_PORT  }}
          script: |
            whoami
            ls -al

          #             PRODUCTION_IP: ${{ secrets.PRODUCTION_IP }}
          # PRODUCTION_PORT: ${{ secrets.PRODUCTION_PORT }}
          # PRODUCTION_USERNAME: ${{ secrets.PRODUCTION_USERNAME }}
          #
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/github_actions_deploy
          chmod 600 ~/.ssh/github_actions_deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRODUCTION_KEY_PRIVATE }} 

      - name: Add SSH host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $PRODUCTION_PORT $PRODUCTION_IP >> ~/.ssh/known_hosts
        env:
          PRODUCTION_IP: ${{ secrets.PRODUCTION_IP }}
          PRODUCTION_PORT: ${{ secrets.PRODUCTION_PORT }}

      - name: SSH and pull latest code
        run: |
          ssh -i ~/.ssh/github_actions_deploy $PRODUCTION_USERNAME@$PRODUCTION_IP -p $PRODUCTION_PORT << 'EOF'
            cd $HOME/test_server

            cat > .env << 'EOF' 
            ROOT_PASSWORD=${ROOT_PASSWORD} 
            DATABASE_NAME=${DATABASE_NAME}
            DATABASE_USER=${DATABASE_USER}
            DATABASE_PASSWORD=${DATABASE_PASSWORD} 
            EOF


            git pull origin main
            chmod +x ./scripts/deploy.sh 
            ./scripts/deploy.sh


          EOF
        env:
          PRODUCTION_IP: ${{ secrets.PRODUCTION_IP }}
          PRODUCTION_PORT: ${{ secrets.PRODUCTION_PORT }}
          PRODUCTION_USERNAME: ${{ secrets.PRODUCTION_USERNAME }}
          ROOT_PASSWORD: ${{ secrets.ROOT_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}


