name: Deploy to Production   

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_IP  }}
          username: ${{ secrets.PRODUCTION_USERNAME  }}
          key: ${{ secrets.PRODUCTION_KEY_PRIVATE  }}
          port: ${{  secrets.PRODUCTION_PORT  }}
          script: |
            # whoami

            REPO_DIR="$HOME/web-cloud-template"
            REPO_URL="https://github.com/anthonyb8/web-cloud-template.git"

            # Clone the repo if it doesn't exist
            if [ ! -d "$REPO_DIR/.git" ]; then
                echo "Repo not found, cloning..."
                git clone "$REPO_URL" "$REPO_DIR"
                cd "$REPO_DIR"
            else
                echo "Repo found, pulling latest changes..."
                cd "$REPO_DIR"
                git pull origin main 
            fi

            # Import application/ TLS envrionment varibles
            cat > .env << 'EOF' 
            ROOT_PASSWORD=${{ secrets.ROOT_PASSWORD }} 
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            CERTBOT_EMAIL=${{ secrets.CERTBOT_EMAIL }}
            DOMAIN_ROOT=${{ secrets.DOMAIN_ROOT }}
            DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
            SSL_CERT=${{ secrets.SSL_CERT }}
            SSL_CERT_KEY=${{secrets.SSL_CERT_KEY }}
            EOF

            # Make deploy script executable and run it
            chmod +x ./scripts/deploy.sh 
            ./scripts/deploy.sh
