name: Deploy to Server

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_KEY_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS_RSA }}" >> ~/.ssh/known_hosts

      - name: SSH and pull latest code
        run: |
          ssh -i ~/.ssh/id_rsa admin@${{ secrets.PRODUCTION_IP }} -p 818 << 'EOF'
            cd /test_server
            git pull origin main
          EOF

